#!/usr/bin/env python
import os
import platform
import sys
"""
ceph-deploy - admin tool for ceph
"""
sys.path.insert(0,'/usr/share/ceph-deploy')
from ceph_deploy.cli import main

if __name__ == '__main__':
    main()
