#!/usr/bin/env python
import os
import platform
import sys
"""
ceph-deploy - admin tool for ceph
"""

if os.path.exists('/usr/share/pyshared/ceph_deploy'):
    sys.path.insert(0,'/usr/share/pyshared/ceph_deploy')
elif os.path.exists('/usr/share/ceph-deploy'):
    sys.path.insert(0,'/usr/share/ceph-deploy')
elif os.path.exists('/usr/share/pyshared/ceph-deploy'):
    sys.path.insert(0,'/usr/share/pyshared/ceph-deploy')
else:
    print >> sys.stderr, '\nceph-deploy modules not installed.'
    sys.exit(1)

from ceph_deploy.cli import main

if __name__ == '__main__':
    main()
